*** Starting uWSGI 2.0.19.1 (64bit) on [Fri Jan 29 14:35:01 2021] ***
compiled with version: 5.4.0 20160609 on 29 January 2021 05:49:28
os: Linux-4.15.0-91-generic #92~16.04.1-Ubuntu SMP Fri Feb 28 14:57:22 UTC 2020
nodename: yanfa-H110SD3-C
machine: x86_64
clock source: unix
detected number of CPU cores: 4
current working directory: /home/yanfa/personal_project/oms_test
writing pidfile to uwsgi.pid
detected binary path: /home/yanfa/.virtualenvs/oms_test/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
chdir() to /home/yanfa/personal_project/oms_test
your processes number limit is 31328
your memory page size is 4096 bytes
detected max file descriptor number: 1048576
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
probably another instance of uWSGI is running on the same address (0.0.0.0:8000).
bind(): Address already in use [core/socket.c line 769]
*** Starting uWSGI 2.0.19.1 (64bit) on [Fri Jan 29 14:35:22 2021] ***
compiled with version: 5.4.0 20160609 on 29 January 2021 05:49:28
os: Linux-4.15.0-91-generic #92~16.04.1-Ubuntu SMP Fri Feb 28 14:57:22 UTC 2020
nodename: yanfa-H110SD3-C
machine: x86_64
clock source: unix
detected number of CPU cores: 4
current working directory: /home/yanfa/personal_project/oms_test
writing pidfile to uwsgi.pid
detected binary path: /home/yanfa/.virtualenvs/oms_test/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
chdir() to /home/yanfa/personal_project/oms_test
your processes number limit is 31328
your memory page size is 4096 bytes
detected max file descriptor number: 1048576
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uWSGI http bound on 0.0.0.0:8000 fd 4
uwsgi socket 0 bound to TCP address 127.0.0.1:37929 (port auto-assigned) fd 3
Python version: 3.7.4 (default, Aug  4 2020, 15:26:49)  [GCC 5.4.0 20160609]
Python main interpreter initialized at 0x2487340
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 166752 bytes (162 KB) for 2 cores
*** Operational MODE: threaded ***
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x2487340 pid: 31755 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 31755)
spawned uWSGI worker 1 (pid: 31756, cores: 2)
spawned uWSGI http 1 (pid: 31758)
[pid: 31756|app: 0|req: 1/1] 127.0.0.1 () {38 vars in 629 bytes} [Fri Jan 29 06:35:45 2021] GET / => generated 0 bytes in 215 msecs (HTTP/1.1 302) 6 headers in 253 bytes (1 switches on core 0)
*** Starting uWSGI 2.0.19.1 (64bit) on [Fri Jan 29 14:46:20 2021] ***
compiled with version: 5.4.0 20160609 on 29 January 2021 05:49:28
os: Linux-4.15.0-91-generic #92~16.04.1-Ubuntu SMP Fri Feb 28 14:57:22 UTC 2020
nodename: yanfa-H110SD3-C
machine: x86_64
clock source: unix
detected number of CPU cores: 4
current working directory: /home/yanfa/personal_project/oms_test
writing pidfile to uwsgi.pid
detected binary path: /home/yanfa/.virtualenvs/oms_test/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
chdir() to /home/yanfa/personal_project/oms_test
your processes number limit is 31328
your memory page size is 4096 bytes
detected max file descriptor number: 1048576
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uWSGI http bound on 0.0.0.0:8000 fd 4
uwsgi socket 0 bound to TCP address 127.0.0.1:43447 (port auto-assigned) fd 3
Python version: 3.7.4 (default, Aug  4 2020, 15:26:49)  [GCC 5.4.0 20160609]
Python main interpreter initialized at 0x16bf2b0
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 166752 bytes (162 KB) for 2 cores
*** Operational MODE: threaded ***
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x16bf2b0 pid: 32504 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 32504)
spawned uWSGI worker 1 (pid: 32505, cores: 2)
spawned uWSGI http 1 (pid: 32507)
[pid: 32505|app: 0|req: 1/1] 127.0.0.1 () {40 vars in 661 bytes} [Fri Jan 29 06:46:27 2021] GET / => generated 0 bytes in 220 msecs (HTTP/1.1 302) 6 headers in 253 bytes (1 switches on core 0)
*** Starting uWSGI 2.0.19.1 (64bit) on [Fri Jan 29 14:50:28 2021] ***
compiled with version: 5.4.0 20160609 on 29 January 2021 05:49:28
os: Linux-4.15.0-91-generic #92~16.04.1-Ubuntu SMP Fri Feb 28 14:57:22 UTC 2020
nodename: yanfa-H110SD3-C
machine: x86_64
clock source: unix
detected number of CPU cores: 4
current working directory: /home/yanfa/personal_project/oms_test
writing pidfile to uwsgi.pid
detected binary path: /home/yanfa/.virtualenvs/oms_test/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
chdir() to /home/yanfa/personal_project/oms_test
your processes number limit is 31328
your memory page size is 4096 bytes
detected max file descriptor number: 1048576
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uWSGI http bound on 0.0.0.0:8000 fd 4
uwsgi socket 0 bound to TCP address 127.0.0.1:41617 (port auto-assigned) fd 3
Python version: 3.7.4 (default, Aug  4 2020, 15:26:49)  [GCC 5.4.0 20160609]
Python main interpreter initialized at 0x173e2b0
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 166752 bytes (162 KB) for 2 cores
*** Operational MODE: threaded ***
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x173e2b0 pid: 32685 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 32685)
spawned uWSGI worker 1 (pid: 32688, cores: 2)
spawned uWSGI http 1 (pid: 32690)
[pid: 32688|app: 0|req: 1/1] 127.0.0.1 () {38 vars in 630 bytes} [Fri Jan 29 06:50:42 2021] GET / => generated 0 bytes in 218 msecs (HTTP/1.1 302) 6 headers in 253 bytes (1 switches on core 0)
Gracefully killing worker 1 (pid: 32688)...
gateway "uWSGI http 1" has been buried (pid: 32690)
...gracefully killing workers...
worker 1 buried after 4 seconds
binary reloading uWSGI...
chdir() to /home/yanfa/personal_project/oms_test
closing all non-uwsgi socket fds > 2 (max_fd = 1048576)...
found fd 3 mapped to socket 0 (127.0.0.1:41617)
running /home/yanfa/.virtualenvs/oms_test/bin/uwsgi
[uWSGI] getting INI configuration from uwsgi.ini
*** Starting uWSGI 2.0.19.1 (64bit) on [Fri Jan 29 10:53:45 2021] ***
compiled with version: 5.4.0 20160609 on 29 January 2021 05:49:28
os: Linux-4.15.0-91-generic #92~16.04.1-Ubuntu SMP Fri Feb 28 14:57:22 UTC 2020
nodename: yanfa-H110SD3-C
machine: x86_64
clock source: unix
detected number of CPU cores: 4
current working directory: /home/yanfa/personal_project/oms_test
detected binary path: /home/yanfa/.virtualenvs/oms_test/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
chdir() to /home/yanfa/personal_project/oms_test
your processes number limit is 31328
your memory page size is 4096 bytes
detected max file descriptor number: 1048576
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uWSGI http bound on 0.0.0.0:8000 fd 5
uwsgi socket 0 bound to TCP address 127.0.0.1:41255 (port auto-assigned) fd 4
Python version: 3.7.4 (default, Aug  4 2020, 15:26:49)  [GCC 5.4.0 20160609]
Python main interpreter initialized at 0x1b16ea0
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 166752 bytes (162 KB) for 2 cores
*** Operational MODE: threaded ***
Traceback (most recent call last):
  File "./oms_test/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
  File "/home/yanfa/.virtualenvs/oms_test/lib/python3.7/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/home/yanfa/.virtualenvs/oms_test/lib/python3.7/site-packages/django/__init__.py", line 19, in setup
    configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
  File "/home/yanfa/.virtualenvs/oms_test/lib/python3.7/site-packages/django/conf/__init__.py", line 83, in __getattr__
    self._setup(name)
  File "/home/yanfa/.virtualenvs/oms_test/lib/python3.7/site-packages/django/conf/__init__.py", line 70, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/yanfa/.virtualenvs/oms_test/lib/python3.7/site-packages/django/conf/__init__.py", line 177, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/home/yanfa/.virtualenvs/oms_test/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "./oms_test/settings.py", line 3, in <module>
    from oms_conf import oms_db, oms_redis, oms_kafka, oms_log
  File "./oms_conf/oms_redis.py", line 4, in <module>
    class RedisConf:
  File "./oms_conf/oms_redis.py", line 17, in RedisConf
    redis_conn = RedisCluster(startup_nodes=_startup_nodes, decode_responses=True, skip_full_coverage_check=True)
  File "/home/yanfa/.virtualenvs/oms_test/lib/python3.7/site-packages/rediscluster/client.py", line 375, in __init__
    **kwargs
  File "/home/yanfa/.virtualenvs/oms_test/lib/python3.7/site-packages/rediscluster/connection.py", line 160, in __init__
    self.nodes.initialize()
  File "/home/yanfa/.virtualenvs/oms_test/lib/python3.7/site-packages/rediscluster/nodemanager.py", line 298, in initialize
    raise RedisClusterException("Redis Cluster cannot be connected. Please provide at least one reachable node.")
rediscluster.exceptions.RedisClusterException: Redis Cluster cannot be connected. Please provide at least one reachable node.
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
*** uWSGI is running in multiple interpreter mode ***
gracefully (RE)spawned uWSGI master process (pid: 32685)
spawned uWSGI worker 1 (pid: 16070, cores: 2)
spawned uWSGI http 1 (pid: 16072)
*** Starting uWSGI 2.0.19.1 (64bit) on [Sat Jan 30 10:20:31 2021] ***
compiled with version: 5.4.0 20160609 on 29 January 2021 05:49:28
os: Linux-4.15.0-91-generic #92~16.04.1-Ubuntu SMP Fri Feb 28 14:57:22 UTC 2020
nodename: yanfa-H110SD3-C
machine: x86_64
clock source: unix
detected number of CPU cores: 4
current working directory: /home/yanfa/personal_project/oms_test
writing pidfile to uwsgi.pid
detected binary path: /home/yanfa/.virtualenvs/oms_test/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
chdir() to /home/yanfa/personal_project/oms_test
your processes number limit is 31328
your memory page size is 4096 bytes
detected max file descriptor number: 1048576
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uWSGI http bound on 0.0.0.0:8000 fd 4
uwsgi socket 0 bound to TCP address 127.0.0.1:43491 (port auto-assigned) fd 3
Python version: 3.7.4 (default, Aug  4 2020, 15:26:49)  [GCC 5.4.0 20160609]
Python main interpreter initialized at 0x1dc62b0
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 166752 bytes (162 KB) for 2 cores
*** Operational MODE: threaded ***
Traceback (most recent call last):
  File "./oms_test/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
  File "/home/yanfa/.virtualenvs/oms_test/lib/python3.7/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/home/yanfa/.virtualenvs/oms_test/lib/python3.7/site-packages/django/__init__.py", line 19, in setup
    configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
  File "/home/yanfa/.virtualenvs/oms_test/lib/python3.7/site-packages/django/conf/__init__.py", line 83, in __getattr__
    self._setup(name)
  File "/home/yanfa/.virtualenvs/oms_test/lib/python3.7/site-packages/django/conf/__init__.py", line 70, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/yanfa/.virtualenvs/oms_test/lib/python3.7/site-packages/django/conf/__init__.py", line 177, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/home/yanfa/.virtualenvs/oms_test/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "./oms_test/settings.py", line 3, in <module>
    from oms_conf import oms_db, oms_redis, oms_kafka, oms_log
  File "./oms_conf/oms_redis.py", line 4, in <module>
    class RedisConf:
  File "./oms_conf/oms_redis.py", line 17, in RedisConf
    redis_conn = RedisCluster(startup_nodes=_startup_nodes, decode_responses=True, skip_full_coverage_check=True)
  File "/home/yanfa/.virtualenvs/oms_test/lib/python3.7/site-packages/rediscluster/client.py", line 375, in __init__
    **kwargs
  File "/home/yanfa/.virtualenvs/oms_test/lib/python3.7/site-packages/rediscluster/connection.py", line 160, in __init__
    self.nodes.initialize()
  File "/home/yanfa/.virtualenvs/oms_test/lib/python3.7/site-packages/rediscluster/nodemanager.py", line 298, in initialize
    raise RedisClusterException("Redis Cluster cannot be connected. Please provide at least one reachable node.")
rediscluster.exceptions.RedisClusterException: Redis Cluster cannot be connected. Please provide at least one reachable node.
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 10006)
spawned uWSGI worker 1 (pid: 10010, cores: 2)
spawned uWSGI http 1 (pid: 10011)
--- no python application found, check your startup logs for errors ---
[pid: 10010|app: -1|req: -1/1] 127.0.0.1 () {38 vars in 630 bytes} [Sat Jan 30 10:20:47 2021] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 10010|app: -1|req: -1/2] 127.0.0.1 () {36 vars in 557 bytes} [Sat Jan 30 10:20:47 2021] GET /favicon.ico => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 1)
--- no python application found, check your startup logs for errors ---
[pid: 10010|app: -1|req: -1/3] 127.0.0.1 () {38 vars in 630 bytes} [Sat Jan 30 10:20:52 2021] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 10010|app: -1|req: -1/4] 127.0.0.1 () {38 vars in 630 bytes} [Sat Jan 30 10:21:24 2021] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 1)
*** Starting uWSGI 2.0.19.1 (64bit) on [Sat Jan 30 10:26:07 2021] ***
compiled with version: 5.4.0 20160609 on 29 January 2021 05:49:28
os: Linux-4.15.0-91-generic #92~16.04.1-Ubuntu SMP Fri Feb 28 14:57:22 UTC 2020
nodename: yanfa-H110SD3-C
machine: x86_64
clock source: unix
detected number of CPU cores: 4
current working directory: /home/yanfa/personal_project/oms_test
writing pidfile to uwsgi.pid
detected binary path: /home/yanfa/.virtualenvs/oms_test/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
chdir() to /home/yanfa/personal_project/oms_test
your processes number limit is 31328
your memory page size is 4096 bytes
detected max file descriptor number: 1048576
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uWSGI http bound on 0.0.0.0:8000 fd 4
uwsgi socket 0 bound to TCP address 127.0.0.1:44229 (port auto-assigned) fd 3
Python version: 3.7.4 (default, Aug  4 2020, 15:26:49)  [GCC 5.4.0 20160609]
Python main interpreter initialized at 0x16a82b0
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 166752 bytes (162 KB) for 2 cores
*** Operational MODE: threaded ***
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x16a82b0 pid: 12734 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 12734)
spawned uWSGI worker 1 (pid: 12738, cores: 2)
spawned uWSGI http 1 (pid: 12740)
[pid: 12738|app: 0|req: 1/1] 127.0.0.1 () {40 vars in 661 bytes} [Sat Jan 30 02:26:11 2021] GET / => generated 0 bytes in 368 msecs (HTTP/1.1 302) 6 headers in 253 bytes (1 switches on core 0)
